Script started on Sun 04 Feb 2018 12:31:09 PM EST
[?1034hbash-4.1$ cd ~/os161/root
bash-4.1$ sys161 kernel
sys161: System/161 release 1.14, compiled Sep  4 2014 10:34:58

OS/161 base system version 1.11
Copyright (c) 2000, 2001, 2002, 2003
   President and Fellows of Harvard College.  All rights reserved.

Put-your-group-name-here's system version 0 (ASST0 #1)

Cpu is MIPS r2000/r3000
336k physical memory available
Device probe...
lamebus0 (system main bus)
emu0 at lamebus0
ltrace0 at lamebus0
ltimer0 at lamebus0
hardclock on ltimer0 (100 hz)
beep0 at ltimer0
rtclock0 at ltimer0
lrandom0 at lamebus0
random0 at lrandom0
lhd0 at lamebus0
lhd1 at lamebus0
lser0 at lamebus0
con0 at lser0
pseudorand0 (virtual)

OS/161 kernel [? for menu]: p /sbin/poweroff <return>
Operation took 0.000159280 seconds
OS/161 kernel [? for menu]: Shutting down.
The system is halted.
sys161: 1012758409 cycles (8676400k, 18u, 1004081991i)
sys161: 4716 irqs 6 exns 0r/0w disk 26r/700w console 8r/0w/3m emufs 0r/0w net
sys161: Elapsed real time: 40.260163 seconds (25.1553 mhz)
sys161: Elapsed virtual time: 40.510336360 seconds (25 mhz)
bash-4.1$ exit

Script done on Sun 04 Feb 2018 12:32:32 PM EST
